### ISSUE TITLE
Opening a New Tab Distorts Sound

### ISSUE THREAD

**Issue by hew** [FormidableLabs/react-music#1]
Steps to reproduce: 
1. `npm start` 
2. Visit localhost:3000
3. Open a new tab. 
4. Focus the new tab. 

Tested in: 

Chrome/Canary
Firefox

**Comment by kenwheeler** [comment]
I presume this is due to backgrounded tabs getting way less processing available to them. I'm wondering if something like this will help:

https://github.com/mohayonao/audio-worker-shim

**Comment by Haroenv** [comment]
Also happens if you move to another space in macOS (so the browser gets backgrounded). This happens with almost everything I've seen using the web audio API though.

**Comment by alavkx** [comment]
After running for about a minute and a half, it starts to struggle rendering the audio (distortion, time slowed). This was with running completely static while being the only tab.

Tested in: Firefox, Ubuntu 16.04

**Comment by jergason** [comment]
In my experience it happens with any WebAudioAPI code, not just React Music.
