### ISSUE TITLE
Switching tabs in Chrome malforms audio

### ISSUE THREAD

**Issue by bnb** [FormidableLabs/react-music#12]
If I leave the untouched demo running and switch to another tab in Chrome, the audio gets really weird and malformed. 

Repro:
1. Clone and start react-music
2. Open `localhost:3000` in Chrome
3. Play
4. Switch to another tab (I had https://github.com/FormidableLabs/react-music/issues/ open)
5. Audio is malformed.

System: El Capitan Latest / 2015 Retina MBP

**Comment by kenwheeler** [comment]
This is sort of a common issue with Web Audio. I'm going to close this and continue in #1 where I'm going to investigate solutions.
