### ISSUE TITLE
ERROR in Cannot find module './options/option-manager'

### ISSUE THREAD

**Issue by yannbertrand** [FormidableLabs/react-music#14]
In master and 1.0.0 branch.

node@6.2.0
npm@3.8.9

```
ERROR in Cannot find module './options/option-manager'
 @ multi main
```

-> No bundle.js seems to be generated

**Comment by kenwheeler** [comment]
Can you try running npm install again?

**Comment by yannbertrand** [comment]
I recloned and reinstalled and it's now working :smile:. Thanks!
