### ISSUE TITLE
Only few notes get played when other tab is focused

### ISSUE THREAD

**Issue by heejongahn** [FormidableLabs/react-music#23]
Hello, I'm not sure if this is a bug or an intended behavior or not, but I couldn't find it in README so I'm reporting it.

I cloned the repo and ran demo, it worked just fine. But as I leave it playing and moved into other tab (in Chrome), only few notes of the song - every three unit beat (I don't know the terminology in English but it goes like sound, mute, mute, sound, mute, mute, ...) get played.

I'm using Chrome Version 52.0.2743.116 (64-bit) on OS X 10.11.6.

**Comment by Haroenv** [comment]
See #1 and #12

**Comment by kenwheeler** [comment]
^
