### ISSUE TITLE
Refactor Internals

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/react-music#3]
While this gets the job done initially, and you can definitely make beats, the internals need to be refactored. Right now, the render treats the tree like a data structure. The refactor should instead have a registry of node relationships so that deep updates can propagate and patch the adjacent audio API, rather than reconstructing it. This would make this like this possible:

``` js
<Reverb>
  <Filter type="lowpass">
    <Synth/>
  </Filter>
</Reverb>
```

The meat and potatoes would be:
- Syncing scheduling between instrument steps and sequencers
- Constructing and patching audio node graphs https://developer.mozilla.org/en-US/docs/Web/API/AudioNode

Would love some input on approaches.

**Comment by kenwheeler** [comment]
To further expand upon this, I thought about this more as a developer and less as a musician. I think a couple of things need to happen.

#### Make steps on sequencer

We should be able to do something like this:

``` js
<Sequencer
  steps=[
    [0, 127, "c1"]
  ]
>
  <Instrument/>
</Sequencer>
```

And further:

``` js
<Sequencer
  steps=[
    [0, 127, "c1"]
  ]
>
  <MIDIOut channel={8}/>
</Sequencer>
```

#### Make instruments

So single oscillator synth tags are basically worthless unless you're making chiptune or something. We need to compose them into patches. Something like:

``` js
<Instrument >
  <Synth type="sine"/>
  <Synth type="sawtooth"/>
</Instrument>
```

Further, this lib shouldn't always loop. There should be a way to design a patch via MIDI in. Imagine this:

``` js
<Instrument midiInputChannel={2} >
  <Synth type="sine"/>
  <Synth type="sawtooth"/>
</Instrument>
```

Where you could play your patches with an external keyboard and have the sound design hot reload!

#### Arrangement

Arrangements could be top level tags, sequencers for sequencers if you will. Sequencers that are nested would not loop, but instead use a repeat prop to build arrangement bars:

``` js
<Arrangement repeat={2} >
  <Sequencer repeat={1} bars={4}/>
  <Sequencer repeat={4} bars={1}/>
</Arrangement>
```

These could be used to compose full length songs! Or at least longer loops with variety.

**Comment by lfittl** [comment]
@kenwheeler Somewhat related question - do you think a refactoring could enable easier state changes, specifically to support re-rendering with changed child props?

My use case is that I have a button outside the `react-music` world that influences how the sequencers behave (by modifying `steps` appropriately when state changes).

Right now the props are only read on the initial mount, but not on consecutive rendering runs. Ideally it would keep playing at the same point in time after a state change, but a clean reset would also work.

**Comment by montao** [comment]
Glad to see that MIDI is not forgotten. My Roland 808 talks via channel 16 with cubase via a converter. When you have anything MIDI I'll be glad to try it.

**Comment by kenwheeler** [comment]
Progress posted here https://github.com/FormidableLabs/react-music/tree/1.0.0

Let me know if I'm crazy
