### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by alavkx** [FormidableLabs/react-music#32]
Very cool project, I was thinking of working on a 3 band EQ, but it may be a bit over my head as I'm rather new to javascript. I'd still love to contribute, is there anything a little simpler you have for me that could get me started? Docs, tests, whatever.
Thanks

**Comment by kenwheeler** [comment]
A 3 band EQ would be awesome. Tests would be cool too, using web-audio-mock and mocha, sinon and chai. Any doc updates would be appreciated if you see opportunity for clarity

**Comment by alavkx** [comment]
Sounds good ill do by best
