### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by davidnaas** [FormidableLabs/react-music#36]
Currently when developing and something is wrong in a component i get the following error:

```
bundle.js:8859 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `AppContainer`.

bundle.js:8400 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `AppContainer`.
```

It's incredibly hard to find the actual error which usually is something simple. It would speed up development a lot if it was possible to make the error messages more explicit.

**Comment by davidnaas** [comment]
After a brief investigation I've come to the conclusion that it's the hot reloading causing it. Reverting that commit brings back normal error messages.

**Comment by kenwheeler** [comment]
hmm, I wonder if we can catch and fix that

**Comment by davidnaas** [comment]
Not sure how. I'm no expert in webpack and hot reloading I'm afraid

**Comment by kenwheeler** [comment]
I'll look into it

**Comment by kenwheeler** [comment]
Closing, as this is react reporting unrelated to this library
