### ISSUE TITLE
this.context.close is not a function

### ISSUE THREAD

**Issue by giacomorebonato** [FormidableLabs/react-music#37]
I am trying to create a UI for React-Music.
Sometimes (I can't understand not always) my component is unable to unmount because in the willUnmount event `this.context.close` is not a function.  
Which could be the fix for this?

<img width="773" alt="screen shot 2016-09-10 at 17 50 57" src="https://cloud.githubusercontent.com/assets/630796/18412134/508e7b12-777f-11e6-9f40-a7cc6af8f933.png">

**Comment by giacomorebonato** [comment]
it should be this.audioContext.close() ... I am trying to understand why it is not like that in my node_modules

**Comment by giacomorebonato** [comment]
I have seen that the error is fixed in Master.  
Usually in this situations I put the git url of the repo in the packages.json, but in this case it doesn't install anything... why?

**Comment by jdan** [comment]
Yep a fix for this is on master :) https://github.com/FormidableLabs/react-music/commit/54d2978d0beeb07a1a0be312f015242a0ae269c7

I also just tried to install with a github URL but it didn't work :(

**Comment by kenwheeler** [comment]
I'll get a release pushed

**Comment by lfittl** [comment]
@kenwheeler Just wanted to poke and see if there's an update on the release? (just ran into this as well)

An alternative would be to use the library through git, but somehow I couldn't get that to work.

**Comment by giacomorebonato** [comment]
Curious to know why it doesn't work through the git url... I have tried to fork the repo and to remove the `.npmignore` but the problem is not that.

**Comment by kenwheeler** [comment]
@lfittl sorry, was in israel. I'll get it pushed out today

**Comment by kenwheeler** [comment]
just pushed 1.0.2. holllllllaaaa
