### ISSUE TITLE
Demo song not working

### ISSUE THREAD

**Issue by johncmunson** [FormidableLabs/react-music#40]
Either the demo song is not working, or it has intentionally been removed from the repo, in which case you may want to consider updating the Readme.

**Comment by aunyks** [comment]
Is demo.js not compiling? @johncmunson

**Comment by kenwheeler** [comment]
where are you seeing this issue? its still very much there

**Comment by johncmunson** [comment]
my apologies. it looks like i was falling victim to a "Node Newbie Error"
http://thisdavej.com/node-newbie-error-npm-refusing-to-install-package-as-a-dependency-of-itself/
