### ISSUE TITLE
Uncaught (in promise) DOMException: Unable to decode audio data

### ISSUE THREAD

**Issue by mahdidavoodi7** [FormidableLabs/react-music#56]
this is my code : 
` constructor(props) {
    super(props);
    this.state = {
      playing: false
    };
  }
handleClick(){
    this.setState({
      playing: !this.state.playing,
    });
  }
return(
      <Song
          playing={this.state.playing}
          tempo={90}
        >
            <Sequencer
              resolution={16}
              bars={1}
            >
              <Sampler
                sample="./Snare.wav"
                steps={[0, 2, 8, 10]}
              />
            </Sequencer>
          </Song>)
`
but this error occured

**Comment by MariaPet** [comment]
To correctly import the sound file you need to do it like this 
`import sound from "./test.mp3"`

and later you can pass it in the Sampler component like this

`<Sampler sample={sound} steps={[0, 4, 8, 12]}/> `

**Comment by mahdidavoodi7** [comment]
the problem was for the location of samples 
i must put them into the public folder 
by the way what you say is true 
th
