### ISSUE TITLE
Safari doesn't deal properly with detune

### ISSUE THREAD

**Issue by Haroenv** [FormidableLabs/react-music#6]
Getting quite a lot of this error: `TypeError: undefined is not an object (evaluating 'source.detune.value = e.args.detune')` when running in Safari (9.2).

![](https://i.imgur.com/sawiejf.png)

**Comment by kenwheeler** [comment]
Interesting. Must be an audioparam issue or something. On it.

**Comment by kenwheeler** [comment]
Fixed in latest
